### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by mtnz0r** [rvzm/zconf#2]
i didnt found your contact :D i open ticket here :DD

do you possible to znc management script for more stuff? and how can i contact you u r on irc?
frenode or quakenet

**Comment by rvzm** [comment]
I'm not on irc much currently, but the easiest way to reach me is via telegram. Honestly right now this repo is not in active development, but it does handle some of znc *status management fairly well. I'm going to be redoing it at some point though to communicate directly with znc via probably http or some other way, it's something I'm gonna look in to. What do you mean by more stuff though?

**Comment by mtnz0r** [comment]
hey i offer free znc for freenode ##bnc4you so i use https://github.com/SISheogorath/eggdrop-znc-management/blob/master/znc.tcl this my friend litte bit help i will fix some bugs add 1-2 more cmds !check etc. but i need more !suspend bla bla and i dont use telegram i have discord :&

**Comment by rvzm** [comment]
So, just so it's clear, this isn't any actual issue with my code, it's a, well I'm not sure what. So as such I'm closing this issue.
